### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by brucelane** [nxgraphics/NxGraphics#1]
hi,
it seems NxGraphicsDeps is now NxGraphicsSdk ?
or where can I find the NxGraphicsDeps repo?

**Comment by PerspectivesLab** [comment]
hi bruce the docs are [here](https://github.com/nxgraphics/NxGraphics/wiki/Compiling-NxGraphics-Dependencies)  
and the dependencies are in the release page [here](https://github.com/nxgraphics/NxGraphics/releases/tag/dependencies_16_01_2016)
concerning the sdk, you need to build first the sources of nxgraphics, and then execute 'BuildSdk.bat' on windows, this will create the sdk.

**Comment by brucelane** [comment]
Merci!
Yes, I was following the documentation page and I haven't seen there was the dependencies in the release page...
More clear now.

**Comment by brucelane** [comment]
Is there a dependency on OpenNi and Kinect?

**Comment by brucelane** [comment]
Maybe there is an error on the wiki:
"open NxGraphicsDeps folder with cmake gui, click configure"
I had to open NxGraphicsDeps/src/Ogre instead, then I had the OGRE_DEPENDENCIES_DIR variable display?
Then on the second Configure click:
I'm now at the step tick CURL_STATICLIB which doesn't show up in the cmake gui

**Comment by brucelane** [comment]
I restarted the whole process:
I am at step "open NxGraphicsDeps folder with cmake gui, click configure."
I get these errors:
OPENNI2_INCLUDE should be set, Did you install openNi Framework
NITE2_INCLUDE should be set, Did you install NiTE2 Framework
KINECTSDK should be set, Did you install Kinect sdk  Framework
Should I install those frameworks?

**Comment by PerspectivesLab** [comment]
no you shouldn't since a lot of these deps are out of support, let me know if you got anything working.. it has been a long while this project wasn't used..

**Comment by brucelane** [comment]
funny, openni.org points to apple.com!
seems I can't generate a proper visual studio project
![image](https://user-images.githubusercontent.com/138158/39466352-b55d0628-4d28-11e8-9ec0-0688aaf7f6b4.png)
